# Generated by Django 4.1.3 on 2023-12-15 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('feed_url', models.URLField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('latitude', models.CharField(blank=True, max_length=400, null=True)),
                ('longitude', models.CharField(blank=True, max_length=400, null=True)),
                ('number_of_reviews', models.PositiveIntegerField(default=0)),
                ('additional_information', models.JSONField(blank=True, help_text='Additional information the business', null=True)),
                ('telephone', models.CharField(blank=True, max_length=300, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'businesses',
                'ordering': ['-created_on', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(max_length=100, unique=True)),
                ('reviewer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reviewer_number_of_reviews', models.PositiveIntegerField(default=0)),
                ('google_review_id', models.CharField(help_text='The comment ID as referenced by Google', max_length=400)),
                ('period', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.TextField(blank=True, max_length=10000, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.business')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['business_id'], name='reviews_bus_busines_025538_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['review_id'], name='reviews_rev_review__ebdfb1_idx'),
        ),
    ]
