# Generated by Django 4.1.5 on 2023-12-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('name', 'address'), name='unique_name_for_address'),
        ),
    ]
